### ISSUE TITLE
Install thunderbird in dockerfile instead of startup

### ISSUE THREAD

**Issue by pagdot** [nelyon/wanderbird#1]
I'd recommend installing thunderbird at image creation instead of startup.

Also I don't know if most of the other software is really required in this docker image.

If you approve this changes, I could create a PR with the changes

**Comment by nelyon** [comment]
> I'd recommend installing thunderbird at image creation instead of startup.
> 
> Also I don't know if most of the other software is really required in this docker image.
> 
> If you approve this changes, I could create a PR with the changes

agree on all counts, do feel free.
